name: Build RenPy

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install RenPy
      uses: PaxlavaGames/renpy-install@v0.3.0
      with:
        version: "8.2.0"
        download_web: "yes"
    - name: Build RenPy
      uses: PaxlavaGames/renpy-web-build@v0.1.2
